# Data Cleaning
Load, validate, merge, and export the raw tables.

In [3]:
import pandas as pd
import numpy as np

# Display settings
pd.set_option("display.max_columns", None)
pd.set_option("display.max_colwidth", None)

In [4]:
# Path to Excel file
file_path = "../data/raw/EduPro_Online_Platform.xlsx"

# Read sheets
users = pd.read_excel(file_path, sheet_name="Users")
courses = pd.read_excel(file_path, sheet_name="Courses")
transactions = pd.read_excel(file_path, sheet_name="Transactions")

In [8]:
print("Users Shape:", users.shape)
print("Courses Shape:", courses.shape)
print("Transactions Shape:", transactions.shape)

Users Shape: (3000, 5)
Courses Shape: (60, 8)
Transactions Shape: (10000, 7)

In [9]:
users.head()

   UserID        UserName  Age  Gender                             Email
0  U00001    wilsonjordan   15    Male            patricia27@hotmail.com
1  U00002        angela22   29  Female             hallrandy@hotmail.com
2  U00003  morrisonamanda   33  Female               ganderson@yahoo.com
3  U00004       fthornton   23  Female  christensencatherine@outlook.com
4  U00005  fostergeoffrey   21    Male            karenfuentes@yahoo.com

In [10]:
courses.head()

,CourseID,CourseName,CourseCategory,CourseType,CourseLevel,CoursePrice,CourseDuration,CourseRating
0,CR00001,Python Basics,Programming,Paid,Beginner,472.28,11.00,4.74
1,CR00002,Java Programming,Programming,Free,Intermediate,0.00,37.70,2.43
2,CR00003,C++ for Beginners,Programming,Free,Beginner,0.00,19.53,3.85
3,CR00004,Advanced Python,Programming,Free,Beginner,0.00,45.13,2.88
4,CR00005,Full Stack Development,Programming,Free,Beginner,0.00,28.68,1.28

In [11]:
transactions.head()

,TransactionID,UserID,CourseID,TransactionDate,Amount,PaymentMethod,TeacherID
0,TT00001,U00003,CR00016,2025-10-25,0.0,PayPal,TC00040
1,TT00002,U00003,CR00037,2025-01-13,0.0,PayPal,TC00040
2,TT00003,U00003,CR00019,2025-03-28,0.0,Bank Transfer,TC00040
3,TT00004,U00004,CR00048,2025-06-02,0.0,Bank Transfer,TC00040
4,TT00005,U00004,CR00060,2025-08-10,0.0,PayPal,TC00042

In [12]:
users.info()

<class 'pandas.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   UserID    3000 non-null   str
 1   UserName  3000 non-null   str
 2   Age       3000 non-null   int64
 3   Gender    3000 non-null   str
 4   Email     3000 non-null   str
dtypes: int64(1), str(4)
memory usage: 239.5 KB

In [13]:
courses.info()

<class 'pandas.DataFrame'>
RangeIndex: 60 entries, 0 to 59
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   CourseID        60 non-null     str
 1   CourseName      60 non-null     str
 2   CourseCategory  60 non-null     str
 3   CourseType      60 non-null     str
 4   CourseLevel     60 non-null     str
 5   CoursePrice     60 non-null     float64
 6   CourseDuration  60 non-null     float64
 7   CourseRating    60 non-null     float64
dtypes: float64(3), str(5)
memory usage: 6.9 KB

In [14]:
transactions.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   TransactionID    10000 non-null  str
 1   UserID           10000 non-null  str
 2   CourseID         10000 non-null  str
 3   TransactionDate  10000 non-null  datetime64[us]
 4   Amount           10000 non-null  float64
 5   PaymentMethod    10000 non-null  str
 6   TeacherID        10000 non-null  str
dtypes: datetime64[us](1), float64(1), str(5)
memory usage: 908.0 KB

In [15]:
print("Users")
print(users.isnull().sum())

print("\nCourses")
print(courses.isnull().sum())

print("\nTransactions")
print(transactions.isnull().sum())

Users
UserID      0
UserName    0
Age         0
Gender      0
Email       0
dtype: int64

Courses
CourseID          0
CourseName        0
CourseCategory    0
CourseType        0
CourseLevel       0
CoursePrice       0
CourseDuration    0
CourseRating      0
dtype: int64

Transactions
TransactionID      0
UserID             0
CourseID           0
TransactionDate    0
Amount             0
PaymentMethod      0
TeacherID          0
dtype: int64

In [16]:
print("Duplicate Users:", users.duplicated().sum())
print("Duplicate Courses:", courses.duplicated().sum())
print("Duplicate Transactions:", transactions.duplicated().sum())

Duplicate Users: 0
Duplicate Courses: 0
Duplicate Transactions: 0

In [17]:
print(users["UserID"].nunique())
print(courses["CourseID"].nunique())
print(transactions["TransactionID"].nunique())

3000
60
10000

Referential Integrity

In [18]:
missing_users = transactions[
    ~transactions["UserID"].isin(users["UserID"])
]

missing_courses = transactions[
    ~transactions["CourseID"].isin(courses["CourseID"])
]

print("Transactions with invalid UserID:", len(missing_users))
print("Transactions with invalid CourseID:", len(missing_courses))

Transactions with invalid UserID: 0
Transactions with invalid CourseID: 0

Create Age Groups

In [19]:
bins = [0, 17, 25, 35, 45, 100]

labels = [
    "<18",
    "18-25",
    "26-35",
    "36-45",
    "45+"
]

users["AgeGroup"] = pd.cut(
    users["Age"],
    bins=bins,
    labels=labels
)

In [20]:
users[["Age", "AgeGroup"]].head()

   Age AgeGroup
0   15      <18
1   29    26-35
2   33    26-35
3   23    18-25
4   21    18-25

In [21]:
users = users[
    [
        "UserID",
        "UserName",
        "Age",
        "AgeGroup",
        "Gender"
    ]
]

In [22]:
courses = courses[
    [
        "CourseID",
        "CourseName",
        "CourseCategory",
        "CourseType",
        "CourseLevel"
    ]
]

In [23]:
transactions = transactions[
    [
        "TransactionID",
        "UserID",
        "CourseID",
        "TransactionDate"
    ]
]

Merge Datasets

In [24]:
merged = pd.merge(
    transactions,
    users,
    on="UserID",
    how="left"
)

In [25]:
merged.head()

,TransactionID,UserID,CourseID,TransactionDate,UserName,Age,AgeGroup,Gender
0,TT00001,U00003,CR00016,2025-10-25,morrisonamanda,33,26-35,Female
1,TT00002,U00003,CR00037,2025-01-13,morrisonamanda,33,26-35,Female
2,TT00003,U00003,CR00019,2025-03-28,morrisonamanda,33,26-35,Female
3,TT00004,U00004,CR00048,2025-06-02,fthornton,23,18-25,Female
4,TT00005,U00004,CR00060,2025-08-10,fthornton,23,18-25,Female

In [26]:
merged = pd.merge(
    merged,
    courses,
    on="CourseID",
    how="left"
)

In [24]:
merged.head()

,TransactionID,UserID,CourseID,TransactionDate,UserName,Age,AgeGroup,Gender,CourseName,CourseCategory,CourseType,CourseLevel
0,TT00001,U00003,CR00016,2025-10-25,morrisonamanda,33,26-35,Female,Digital Marketing,Marketing,Free,Intermediate
1,TT00002,U00003,CR00037,2025-01-13,morrisonamanda,33,26-35,Female,Scrum Essentials,Project Management,Free,Intermediate
2,TT00003,U00003,CR00019,2025-03-28,morrisonamanda,33,26-35,Female,Content Marketing,Marketing,Free,Advanced
3,TT00004,U00004,CR00048,2025-06-02,fthornton,23,18-25,Female,AI Ethics,Artificial Intelligence,Free,Beginner
4,TT00005,U00004,CR00060,2025-08-10,fthornton,23,18-25,Female,Content Creation,Digital Marketing,Free,Beginner

In [27]:
print(merged.shape)

print()

print(merged.isnull().sum())

(10000, 12)

TransactionID      0
UserID             0
CourseID           0
TransactionDate    0
UserName           0
Age                0
AgeGroup           0
Gender             0
CourseName         0
CourseCategory     0
CourseType         0
CourseLevel        0
dtype: int64

In [26]:
merged.to_csv(
    "../data/processed/merged_data.csv",
    index=False
)

print("Processed dataset saved successfully!")

Processed dataset saved successfully!

In [28]:
merged.describe(include="all")

,TransactionID,UserID,CourseID,TransactionDate,UserName,Age,AgeGroup,Gender,CourseName,CourseCategory,CourseType,CourseLevel
count,10000,10000,10000,10000,10000,10000.000000,10000,10000,10000,10000,10000,10000
unique,10000,3000,60,NaN,3000,NaN,3,2,58,12,2,3
top,TT00001,U00018,CR00021,NaN,nicole97,NaN,26-35,Female,Deep Learning,Data Science,Free,Beginner
freq,1,16,196,NaN,16,NaN,4799,5078,334,916,6403,3573
mean,NaN,NaN,NaN,2025-07-01 03:50:32.640000,NaN,24.965700,NaN,NaN,NaN,NaN,NaN,NaN
min,NaN,NaN,NaN,2025-01-01 00:00:00,NaN,15.000000,NaN,NaN,NaN,NaN,NaN,NaN
25%,NaN,NaN,NaN,2025-04-02 00:00:00,NaN,20.000000,NaN,NaN,NaN,NaN,NaN,NaN
50%,NaN,NaN,NaN,2025-06-30 00:00:00,NaN,25.000000,NaN,NaN,NaN,NaN,NaN,NaN
75%,NaN,NaN,NaN,2025-09-28 00:00:00,NaN,30.000000,NaN,NaN,NaN,NaN,NaN,NaN
max,NaN,NaN,NaN,2025-12-30 00:00:00,NaN,35.000000,NaN,NaN,NaN,NaN,NaN,NaN
std,NaN,NaN,NaN,NaN,NaN,6.051858,NaN,NaN,NaN,NaN,NaN,NaN

In [29]:
merged["Year"] = merged["TransactionDate"].dt.year
merged["Month"] = merged["TransactionDate"].dt.month
merged["MonthName"] = merged["TransactionDate"].dt.strftime("%B")
merged["Quarter"] = merged["TransactionDate"].dt.quarter
merged["DayOfWeek"] = merged["TransactionDate"].dt.day_name()

In [30]:
merged.head()

,TransactionID,UserID,CourseID,TransactionDate,UserName,Age,AgeGroup,Gender,CourseName,CourseCategory,CourseType,CourseLevel,Year,Month,MonthName,Quarter,DayOfWeek
0,TT00001,U00003,CR00016,2025-10-25,morrisonamanda,33,26-35,Female,Digital Marketing,Marketing,Free,Intermediate,2025,10,October,4,Saturday
1,TT00002,U00003,CR00037,2025-01-13,morrisonamanda,33,26-35,Female,Scrum Essentials,Project Management,Free,Intermediate,2025,1,January,1,Monday
2,TT00003,U00003,CR00019,2025-03-28,morrisonamanda,33,26-35,Female,Content Marketing,Marketing,Free,Advanced,2025,3,March,1,Friday
3,TT00004,U00004,CR00048,2025-06-02,fthornton,23,18-25,Female,AI Ethics,Artificial Intelligence,Free,Beginner,2025,6,June,2,Monday
4,TT00005,U00004,CR00060,2025-08-10,fthornton,23,18-25,Female,Content Creation,Digital Marketing,Free,Beginner,2025,8,August,3,Sunday

In [31]:
merged.to_csv(
    "../data/processed/merged_data.csv",
    index=False
)